### ISSUE TITLE
Use semi colon instead of go to execute command

### ISSUE THREAD

**Issue by anupinder** [scgray/jsqsh#4]
Hi,
    Is there any way to use semi colon  instead of go keyword to execute command in jsqsh

**Comment by scgray** [comment]
Hi. Yes, you can use semicolon however you need to tell jsqsh roughly what dialect of SQL your database speaks in order to enable it.  If you have one of the newer builds of jsqsh you can enter the setup wizard (jsqsh --setup) and edit the driver, under SQL Parser you can choose ANSI SQL, T-SQL or PL/SQL.  It doesn't matter if you don't see your specific dialect, the main thing the feature does is to try to make the handling of semi-colon "smart".   For example, in PL/SQL jsqsh will try to distinguish between a semicolon as the end of a statement in a compound block vs. a semicolon that is causing a "go" to be issued.

If you tell me the driver and a good default I can also make it the default permanently in the code.

**Comment by anupinder** [comment]
Hi Scott,
           Nice to hear back from you.Your contribution to open source community with sqsh and now with jsqsh is tremendous.
I was using Microsoft JDBC Driver and your suggestion worked and I am able to work without go to execute commands by using both T SQL and ANSI Parser.
Thanks a lot for that.
I had one more doubt and I would be greatful if you can clarify that one also.
   I am using Microsoft JDBC Driver with JavaKerberos Security to connect to  SQL Server.I am able to connect to SQL Server successfully with that.Each time I try to connect with already created connection,it prompts for password ,I hit enter and it reads keytab file and works perfectly fine.
I was curious how I can make it work for a cron job or shell script  as it prompts for password each time.Is there any builtin way to bypass that prompt where it asks for password.
    I am not an expert so apology if my question looks ridicolous.

Thanks,
Anupinder Rai

**Comment by scgray** [comment]
Anupinder, 

I haven't worked with a Kerberos enabled driver before, so I'm glad you are trying because I'm interested in how to make jsqsh friendlier in that sort of environment.   For now, can you try to set the password in the connection management window?  You may have to set the password to some garbage or maybe just a space.   Let me know if that works.  if it doesn't I may need to add an option to indicate that the connection doesn't require a password at all.

Also, if you don't mind, can you share your entry for the connection from $HOME/.jsqsh/connections.xml and, if you modified the driver, the driver definition from $HOME/.jsqsh/drivers.xml?  I haven't worked with SQL Server in many years, so I don't really maintain the entries built in to jsqsh today, so it would be nice to update them if necessary.

**Comment by anupinder** [comment]
Hi Scott,
           I had tried to put fake password and it does not help.

Here is the content of Drivers.xml 

 </Driver>
   <Driver name="MSSQL"
           url="jdbc:sqlserver://${server};database=master;integratedSecurity=true;authenticationScheme=JavaKerberos"
           class="com.microsoft.sqlserver.jdbc.SQLServerDriver"
           target="Microsoft Driver for sql server Custom"
           analyzer="org.sqsh.analyzers.TSQLAnalyzer"
           normalizer="org.sqsh.normalizer.NullNormalizer">
      <Variable name="server"><![CDATA[server1.stsci.edu]]></Variable>
      <Property name="java.security.auth.login.config"><![CDATA[/home/arai/SQLJDBCDriver.conf]]></Property>
   </Driver>

Here is the content of connections.xml 

 <connections>
  <connection name="conn1"
               driver="MSSQL"
               server="server1.domainname"
   >
      <username><![CDATA[user]]></username>
      <properties>
          <property name="portNumber"><![CDATA[1433]]></property>
          <property name="authenticationScheme"><![CDATA[javaKerberos]]></property>
          <property name="java.security.auth.login.config"><![CDATA[/home/user1/SQLJDBCDriver.conf]]></property>
          <property name="password"><![CDATA[zjklfvsajlfd]]></property>
          <property name="integratedSecurity"><![CDATA[true]]></property>
      </properties>
   </connection>
  </connections>

The contents of file /home/user1/SQLJDBCDriver.conf are like 

SQLJDBCDriver {
   com.sun.security.auth.module.Krb5LoginModule required principal=user1 useKeyTab=true keyTab="/home/user1/user1.keytab";
};

I had created that keytab file with 

ktutil
addent -password -p <username> -k 1 -e aes256-cts
wkt <filename>.keytab
exit


Thanks a lot for quick reply.
Please let me know if I send some more information.



Thanks,
Anupinder  Rai

**Comment by anupinder** [comment]
It worked with grabage password.


Thanks
