### ISSUE TITLE
Password encryption in Configuration File

### ISSUE THREAD

**Issue by matz3ibm** [scgray/jsqsh#59]
Hi Scott,

when the password is set at the Moment via jsqsh and saved in the configuration file, a standard security check is failing because the file is scanned and the weak encryption is detected.
Would it be possible to use a better encryption algorithm for the password in the configuration file?

regards
Matthias

**Comment by scgray** [comment]
Hey Mattias! 

It is my understanding that Gustavo will be working on a PR for this. I'll ping him and see if he is (and get his GitHub id to assign this ticket to him), otherwise I can try to work on it in my spare time. The main trick is that it will need to be made in a 2.x branch because I'm not sure that 3.0 is ready yet for general purpose use.

**Comment by matz3ibm** [comment]
works now :+1: updated at customer - well done!

**Comment by scgray** [comment]
@matz3ibm There was no code added to support this in this repository. Maybe it was fixed in an in-house branch?
